### ISSUE TITLE
Shiro tv beta bugs

### ISSUE THREAD

**Issue by JimZiii** [Blatzar/shiro-app#33]
Can't fast forward or rewind using the slider. Tried both remote and mouse/keyboard.

Second issue i noticed was the shortcuts to play next episode of watched animes, using the remotes d-pad with the video playing doesn't FF or rewind, instead its still moving around on the homepage. You're even able to start another anime or the same anime twice and have the audio of both playing.

The rest isn't really a big deal.
-It's impossible to reach the dub/sub switch button on anime pages using a remote.
-Same with closing those drop downs the episodes are divided in.
-The microphone next to the search bar can't be used
-To play episodes takes a second longer than before, but i think that's depending on the source used

Not sure if you pulled it down right after i downloaded it, i can't find it now. But i thought I'd let you know what i found anyways for the next release.
The rest worked fine so far, it is tracking episodes played and time played, multiple sources works fine.
Can't wait for the next release.

Also, I'm on a nvidia shield if that makes any difference.

**Comment by Blatzar** [comment]
> Can't fast forward or rewind using the slider. Tried both remote and mouse/keyboard.

I will fix that later

> Second issue i noticed was the shortcuts to play next episode of watched animes, using the remotes d-pad with the video playing doesn't FF or rewind, instead its still moving around on the homepage. You're even able to start another anime or the same anime twice and have the audio of both playing.

Good observation, It's already patched, but I haven't pushed an update yet

> -It's impossible to reach the dub/sub switch button on anime pages using a remote.

Will fix, I have noticed, I will hopefully redesign the entire anime info page

> -Same with closing those drop downs the episodes are divided in.

I have no idea how to fix this in a good way so it's probably just going to be a feature

> The microphone next to the search bar can't be used

Thanks, Ill remove

> -To play episodes takes a second longer than before, but i think that's depending on the source used

Yeah right now it loads all the links instead of one, I'm working on making it start right as shiro is loaded and load the others in the background

> Not sure if you pulled it down right after i downloaded it, i can't find it now. But i thought I'd let you know what i found anyways for the next release.
The rest worked fine so far, it is tracking episodes played and time played, multiple sources works fine.

Apparently having android TV interfeared with updating from the phone version hence I pulled it down, I've fixed it now, but the old versions will still be unable to upgrade to 2.2.2 if I also have a tv apk attached due to an oversight.

Thanks for the extensive testing!

**Comment by Blatzar** [comment]
https://mega.nz/file/BKYw2LxJ#zEde1e-jCayC2OFuxiH40pQETrA5OCjoeKgft5AaHJY

for 2.2.2 :)
