### ISSUE TITLE
Quality option

### ISSUE THREAD

**Issue by knightblood135** [Blatzar/shiro-app#59]
Please add quality option for users to select there 
Desire quality 360p, 480p, 720p , ect. 
I am just saying because you made a mobile app
And lot lot's of user want to save there data...... Duh.
Although it's a very great app. 
With anilist login.. Pretty interesting I love it ❤ 

But please consider quality option in next update..

**Comment by Blatzar** [comment]
See https://github.com/Blatzar/shiro-app/issues/51#issuecomment-865948913

**Comment by knightblood135** [comment]
What i am saying that user have no freedom to choose there
Specific quality 
If there than it will be helpful 
Changing souces is not like changing quality freely

**Comment by Blatzar** [comment]
Of course user doesn't have full quality control on all videos like YouTube, but that's because it's literally impossible to add without using other sites. I've already added all possible sources on Shiro and most videos simply lack quality options, I cannot give you 360, 480, 720p if all I get from the site is a 1080p mp4.
