### ISSUE TITLE
Shiro TV Buffering

### ISSUE THREAD

**Issue by AbyssalAssassin1010** [Blatzar/shiro-app#95]
Hi Devs, is it okay for me to inquire on why recently Shiro TV had been buffering quite a lot when watching animes? And weirdly on some title like Gintama, it even ewfused to load after certain extent and some won't enable the next episode feature.

**Comment by Blatzar** [comment]
Sorry I forgot to adress this. 
Unfortunately I cannot really improve or fix video buffering as it's in the hands of exoplayer (a very professional project). This means that when it has successfully loaded the links, but just buffers a lot it's very likely due to bad internet connection to the TV (try plugging in ethernet if possible) or low bandwidth from the server (nothing either of us can do to fix)
